server:
  port: 8080
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://rubensql/bdpractica
    username: ruben
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
